export const planData = {
  MainPlan: [
    // --- ANTWERP 10 MILES: PHASE 1 ---
    {
      "Week Start": "11/03/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 8 km (3x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 13 km",
      Sun: "REST",
      "Total Run km": 32,
    },
    {
      "Week Start": "11/10/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 8 km (3x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 14 km",
      Sun: "REST",
      "Total Run km": 33,
    },
    {
      "Week Start": "11/17/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 9 km (2x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 15 km",
      Sun: "REST",
      "Total Run km": 35,
    },
    {
      "Week Start": "11/24/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 4 km Easy",
      Thu: "Run 5 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 12 km",
      Sun: "REST",
      "Total Run km": 28,
    },
    {
      "Week Start": "12/01/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 9 km (2x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 6 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 16 km",
      Sun: "REST",
      "Total Run km": 37,
    },
    {
      "Week Start": "12/08/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 9 km (3x12min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 7 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 17 km",
      Sun: "REST",
      "Total Run km": 39,
    },
    {
      "Week Start": "12/15/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 10 km (20min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 7 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 18 km",
      Sun: "REST",
      "Total Run km": 41,
    },
    {
      "Week Start": "12/22/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Deload",
      Mon: "Run 8 km (2x12min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 14 km",
      Sun: "REST",
      "Total Run km": 33,
    },
    {
      "Week Start": "12/29/2025",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 10 km (25min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 7 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 18 km",
      Sun: "REST",
      "Total Run km": 41,
    },
    {
      "Week Start": "01/05/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 10 km (5x1km @ 10k)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 8 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 19 km",
      Sun: "REST",
      "Total Run km": 43,
    },
    {
      "Week Start": "01/12/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 11 km (2x20min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Run 8 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 20 km",
      Sun: "REST",
      "Total Run km": 46,
    },
    {
      "Week Start": "01/19/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Deload",
      Mon: "Run 8 km (2x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 16 km",
      Sun: "REST",
      "Total Run km": 35,
    },
    {
      "Week Start": "01/26/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 10 km (4x1.2km @ 10k)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Run 8 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 19 km",
      Sun: "REST",
      "Total Run km": 44,
    },
    {
      "Week Start": "02/02/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 11 km (30min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Run 8 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 20 km",
      Sun: "REST",
      "Total Run km": 46,
    },
    {
      "Week Start": "02/09/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 11 km (3x10min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Run 8 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 21 km",
      Sun: "REST",
      "Total Run km": 47,
    },
    {
      "Week Start": "02/16/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Deload",
      Mon: "Run 8 km (2x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 7 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 17 km",
      Sun: "REST",
      "Total Run km": 37,
    },
    {
      "Week Start": "02/23/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 12 km (2x15min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Run 8 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 20 km",
      Sun: "REST",
      "Total Run km": 47,
    },
    {
      "Week Start": "03/02/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 12 km (3x12min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Run 8 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 22 km",
      Sun: "REST",
      "Total Run km": 50,
    },
    {
      "Week Start": "03/09/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Up",
      Mon: "Run 12 km (2x20min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Run 9 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 22 km",
      Sun: "REST",
      "Total Run km": 51,
    },
    {
      "Week Start": "03/16/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Deload",
      Mon: "Run 9 km (20min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 7 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 18 km",
      Sun: "REST",
      "Total Run km": 40,
    },
    {
      "Week Start": "03/23/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Peak",
      Mon: "Run 12 km (3x15min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Run 8 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 20 km",
      Sun: "REST",
      "Total Run km": 48,
    },
    {
      "Week Start": "03/30/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Taper 1",
      Mon: "Run 10 km (2x10min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Run 7 km + 6x hill sprints",
      Fri: "Strength Day B",
      Sat: "Long Run 14 km",
      Sun: "REST",
      "Total Run km": 37,
    },
    {
      "Week Start": "04/06/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Taper 2",
      Mon: "Run 8 km (3x5min @ 10M pace)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Run 6 km + 6x strides",
      Fri: "Strength Day B",
      Sat: "Long Run 10 km",
      Sun: "REST",
      "Total Run km": 29,
    },
    {
      "Week Start": "04/13/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Taper 3",
      Mon: "Run 7 km (2x5min @ 10M pace)",
      Tue: "Light mobility",
      Wed: "Run 5 km Easy",
      Thu: "Run 5 km + 6x strides",
      Fri: "OFF",
      Sat: "Long Run 8 km",
      Sun: "REST",
      "Total Run km": 25,
    },
    {
      "Week Start": "04/20/2026",
      Phase: "Phase 1: Antwerp 10 Miler",
      "Week Type": "Race",
      Mon: "Run 5 km (2x3min @ 10M pace)",
      Tue: "Light mobility",
      Wed: "OFF",
      Thu: "Run 4 km (Easy + 4 strides)",
      Fri: "OFF",
      Sat: "OFF",
      Sun: "RACE: Antwerp 10 Miles!",
      "Total Run km": 9,
    },
    // --- MARATHON TRAINING PHASE 2 ---
    {
      "Week Start": "04/27/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Recovery",
      Mon: "Run 5 km Easy (<140 bpm)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 6 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 5 km Easy + 4x Strides",
      Sat: "Long Run 14 km (Easy)",
      Sun: "REST",
      "Total Run km": 30,
    },
    {
      "Week Start": "05/04/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Calf Recovery",
      Mon: "OFF",
      Tue: "Strength Day + Bike 30 min Easy Spin",
      Wed: "Swim 45 min OR Bike 45 min Easy",
      Thu: "Run 3 km (Walk/Run Test for Calf)",
      Fri: "OFF",
      Sat: "Bike 60 min Easy Spin",
      Sun: "Run 5 km Easy (If Thursday was 100% painless)",
      "Total Run km": 8,
    },
    {
      "Week Start": "05/11/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 7 km (1km WU, 4 km @ 5:00/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 8 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 6 km Easy",
      Sat: "Long Run 14 km (Easy)",
      Sun: "REST",
      "Total Run km": 35,
    },
    {
      "Week Start": "05/18/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 8 km (1km WU, 5 km @ 5:00/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 9 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 7 km Easy + 4x Strides",
      Sat: "Long Run 16 km (Easy)",
      Sun: "REST",
      "Total Run km": 40,
    },
    {
      "Week Start": "05/25/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 8 km (1km WU, 2x3 km @ 4:55/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 10 km Easy (<140 bpm)",
      Thu: "Bike 75 min Easy/Steady",
      Fri: "Run 7 km Easy + 4x Strides",
      Sat: "Long Run 18 km (Easy)",
      Sun: "REST",
      "Total Run km": 43,
    },
    {
      "Week Start": "06/01/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Deload",
      Mon: "Run 6 km (1km WU, 3 km @ 4:55/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 7 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 5 km Easy + 4x Strides",
      Sat: "Long Run 14 km (Easy)",
      Sun: "REST",
      "Total Run km": 32,
    },
    {
      "Week Start": "06/08/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 8 km (1km WU, 5 km @ 4:55/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 10 km Easy (<140 bpm)",
      Thu: "Bike 75 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 20 km (incl. 4 km @ MP)",
      Sun: "REST",
      "Total Run km": 46,
    },
    {
      "Week Start": "06/15/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 9 km (1km WU, 6 km @ 4:50/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 11 km Easy (<140 bpm)",
      Thu: "Bike 75 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 22 km (incl. 2x15min @ MP)",
      Sun: "REST",
      "Total Run km": 50,
    },
    {
      "Week Start": "06/22/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 10 km (1km WU, 2x3.5 km @ 4:50/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 12 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 24 km (incl. 2x20min @ MP)",
      Sun: "REST",
      "Total Run km": 54,
    },
    {
      "Week Start": "06/29/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Deload",
      Mon: "Run 6 km (1km WU, 3 km @ 4:50/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 8 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 6 km Easy + 4x Strides",
      Sat: "Long Run 16 km (Easy)",
      Sun: "REST",
      "Total Run km": 36,
    },
    {
      "Week Start": "07/06/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 10 km (1km WU, 6 km @ 4:50/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 12 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 26 km (Easy, Time on feet)",
      Sun: "REST",
      "Total Run km": 56,
    },
    {
      "Week Start": "07/13/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 10 km (1km WU, 7 km @ 4:45/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 14 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 28 km (incl. 2x20min @ MP)",
      Sun: "REST",
      "Total Run km": 60,
    },
    {
      "Week Start": "07/20/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 11 km (1km WU, 2x4 km @ 4:45/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 15 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 30 km (incl. 3x20min @ MP)",
      Sun: "REST",
      "Total Run km": 64,
    },
    {
      "Week Start": "07/27/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Deload",
      Mon: "Run 7 km (1km WU, 3 km @ 4:45/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 9 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 6 km Easy + 4x Strides",
      Sat: "Long Run 20 km (Easy)",
      Sun: "REST",
      "Total Run km": 42,
    },
    {
      "Week Start": "08/03/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 10 km (1km WU, 7 km @ 4:45/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 14 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 30 km (incl. 2x25min @ MP)",
      Sun: "REST",
      "Total Run km": 62,
    },
    {
      "Week Start": "08/10/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 11 km (1km WU, 8 km @ 4:40/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 14 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 32 km (incl. 3x20min @ MP)",
      Sun: "REST",
      "Total Run km": 66,
    },
    {
      "Week Start": "08/17/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 12 km (1km WU, 3x3 km @ 4:40/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 16 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 34 km (incl. 2x30min @ MP)",
      Sun: "REST",
      "Total Run km": 70,
    },
    {
      "Week Start": "08/24/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Deload",
      Mon: "Run 8 km (1km WU, 4 km @ 4:40/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 10 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 6 km Easy + 4x Strides",
      Sat: "Long Run 22 km (Easy)",
      Sun: "REST",
      "Total Run km": 46,
    },
    {
      "Week Start": "08/31/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 11 km (1km WU, 8 km @ 4:40/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 15 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 32 km (incl. 4x15min @ MP)",
      Sun: "REST",
      "Total Run km": 66,
    },
    {
      "Week Start": "09/07/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Up",
      Mon: "Run 12 km (1km WU, 9 km @ 4:35/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 16 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 34 km (incl. 3x25min @ MP)",
      Sun: "REST",
      "Total Run km": 70,
    },
    {
      "Week Start": "09/14/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Peak",
      Mon: "Run 12 km (1km WU, 2x4.5 km @ 4:35/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 16 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 10 km Easy + 4x Strides",
      Sat: "Long Run 36 km (Pure Easy/Time on feet)",
      Sun: "REST",
      "Total Run km": 74,
    },
    {
      "Week Start": "09/21/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Deload",
      Mon: "Run 8 km (1km WU, 4 km @ 4:35/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 12 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 6 km Easy + 4x Strides",
      Sat: "Long Run 24 km (incl. 2x15m @ MP)",
      Sun: "REST",
      "Total Run km": 50,
    },
    {
      "Week Start": "09/28/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Taper 1",
      Mon: "Run 11 km (1km WU, 6 km @ 4:35/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 15 km Easy (<140 bpm)",
      Thu: "Bike 90 min Easy/Steady",
      Fri: "Run 8 km Easy + 4x Strides",
      Sat: "Long Run 30 km (incl. 15km continuous @ MP)",
      Sun: "REST",
      "Total Run km": 64,
    },
    {
      "Week Start": "10/05/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Taper 2",
      Mon: "Run 8 km (1km WU, 3 km @ 4:35/km, CD)",
      Tue: "Strength Day + Optional Bike 45 min",
      Wed: "Run 10 km Easy (<140 bpm)",
      Thu: "Bike 60 min Easy/Steady",
      Fri: "Run 5 km Easy + 4x Strides",
      Sat: "Long Run 16 km (Easy)",
      Sun: "REST",
      "Total Run km": 39,
    },
    {
      "Week Start": "10/12/2026",
      Phase: "Phase 2: Antwerp Marathon",
      "Week Type": "Race",
      Mon: "Run 5 km Easy",
      Tue: "Mobility / Light Spin",
      Wed: "Run 4 km Easy + 4x Strides",
      Thu: "OFF",
      Fri: "Run 4 km Shakeout",
      Sat: "OFF",
      Sun: "RACE: Antwerp Marathon!",
      "Total Run km": 55,
    },

    // --- IRONMAN TRAINING PHASE 3 ---
    {
      "Week Start": "10/19/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Recovery",
      Mon: "OFF",
      Tue: "Light walk / mobility",
      Wed: "Run 3-5 km Easy (optional)",
      Thu: "Light walk / mobility",
      Fri: "OFF",
      Sat: "Bike: 30-45 min Easy Spin (optional)",
      Sun: "OFF",
      "Total Run km": 5,
    },
    {
      "Week Start": "10/26/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Recovery",
      Mon: "OFF",
      Tue: "Light walk / mobility",
      Wed: "Run 3-5 km Easy (optional)",
      Thu: "Light walk / mobility",
      Fri: "OFF",
      Sat: "Bike: 30-45 min Easy Spin (optional)",
      Sun: "OFF",
      "Total Run km": 5,
    },
    {
      "Week Start": "11/02/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 8 km (3x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Bike: 60 min (incl. 2x15min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 1.5 hours Easy/Steady",
      Sun: "Long Run 12 km",
      "Total Run km": 26,
    },
    {
      "Week Start": "11/09/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 8 km (3x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Bike: 60 min (incl. 2x15min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 1.6 hours Easy/Steady",
      Sun: "Long Run 12 km",
      "Total Run km": 26,
    },
    {
      "Week Start": "11/16/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 8 km (3x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 6 km Easy",
      Thu: "Bike: 60 min (incl. 2x15min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 1.8 hours Easy/Steady",
      Sun: "Long Run 12 km",
      "Total Run km": 26,
    },
    {
      "Week Start": "11/23/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Bike: 60 min (incl. 2x15min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 1.0 hours Easy/Steady",
      Sun: "Long Run 10 km",
      "Total Run km": 22,
    },
    {
      "Week Start": "11/30/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 9 km (3x11min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Bike: 70 min (incl. 2x17min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.3 hours Easy/Steady",
      Sun: "Long Run 14 km",
      "Total Run km": 30,
    },
    {
      "Week Start": "12/07/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 9 km (3x11min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Bike: 70 min (incl. 2x17min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.4 hours Easy/Steady",
      Sun: "Long Run 14 km",
      "Total Run km": 30,
    },
    {
      "Week Start": "12/14/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 9 km (3x11min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 7 km Easy",
      Thu: "Bike: 70 min (incl. 2x17min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.5 hours Easy/Steady",
      Sun: "Long Run 14 km",
      "Total Run km": 30,
    },
    {
      "Week Start": "12/21/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Bike: 70 min (incl. 2x17min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 1.6 hours Easy/Steady",
      Sun: "Long Run 10 km",
      "Total Run km": 22,
    },
    {
      "Week Start": "12/28/2026",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 10 km (3x12min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Bike: 80 min (incl. 2x19min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.8 hours Easy/Steady",
      Sun: "Long Run 16 km",
      "Total Run km": 34,
    },
    {
      "Week Start": "01/04/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 10 km (3x12min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Bike: 80 min (incl. 2x19min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.9 hours Easy/Steady",
      Sun: "Long Run 16 km",
      "Total Run km": 34,
    },
    {
      "Week Start": "01/11/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 10 km (3x12min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 8 km Easy",
      Thu: "Bike: 80 min (incl. 2x19min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 3.0 hours Easy/Steady",
      Sun: "Long Run 16 km",
      "Total Run km": 34,
    },
    {
      "Week Start": "01/18/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Bike: 80 min (incl. 2x19min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.0 hours Easy/Steady",
      Sun: "Long Run 12 km",
      "Total Run km": 24,
    },
    {
      "Week Start": "01/25/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 11 km (3x13min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 9 km Easy",
      Thu: "Bike: 90 min (incl. 2x21min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 3.4 hours Easy/Steady",
      Sun: "Long Run 18 km",
      "Total Run km": 38,
    },
    {
      "Week Start": "02/01/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 11 km (3x13min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 9 km Easy",
      Thu: "Bike: 90 min (incl. 2x21min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 3.5 hours Easy/Steady",
      Sun: "Long Run 18 km",
      "Total Run km": 38,
    },
    {
      "Week Start": "02/08/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 11 km (3x13min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 9 km Easy",
      Thu: "Bike: 90 min (incl. 2x21min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 3.6 hours Easy/Steady",
      Sun: "Long Run 18 km",
      "Total Run km": 38,
    },
    {
      "Week Start": "02/15/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Bike: 90 min (incl. 2x21min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 2.6 hours Easy/Steady",
      Sun: "Long Run 14 km",
      "Total Run km": 26,
    },
    {
      "Week Start": "02/22/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 12 km (3x14min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 10 km Easy",
      Thu: "Bike: 100 min (incl. 2x23min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 4.0 hours Easy/Steady",
      Sun: "Long Run 20 km",
      "Total Run km": 42,
    },
    {
      "Week Start": "03/01/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 12 km (3x14min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 10 km Easy",
      Thu: "Bike: 100 min (incl. 2x23min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 4.1 hours Easy/Steady",
      Sun: "Long Run 20 km",
      "Total Run km": 42,
    },
    {
      "Week Start": "03/08/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 12 km (3x14min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 10 km Easy",
      Thu: "Bike: 100 min (incl. 2x23min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 4.2 hours Easy/Steady",
      Sun: "Long Run 20 km",
      "Total Run km": 42,
    },
    {
      "Week Start": "03/15/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Run 7 km (2x10min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 5 km Easy",
      Thu: "Bike: 100 min (incl. 2x23min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 3.2 hours Easy/Steady",
      Sun: "Long Run 16 km",
      "Total Run km": 28,
    },
    {
      "Week Start": "03/22/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 13 km (3x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 11 km Easy",
      Thu: "Bike: 110 min (incl. 2x25min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 4.6 hours Easy/Steady",
      Sun: "Long Run 22 km",
      "Total Run km": 46,
    },
    {
      "Week Start": "03/29/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Base",
      Mon: "Run 13 km (3x15min tempo)",
      Tue: "Strength Day A",
      Wed: "Run 11 km Easy",
      Thu: "Bike: 110 min (incl. 2x25min Tempo)",
      Fri: "Strength Day B",
      Sat: "Long Bike: 4.7 hours Easy/Steady",
      Sun: "Long Run 22 km",
      "Total Run km": 46,
    },
    {
      "Week Start": "04/05/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.0 km (Technique) + Strength A",
      Tue: "Bike: 90 min (3x15min @ IM Pace)",
      Wed: "Swim: 2.2 km (Endurance)",
      Thu: "Run: 10 km (2x15min @ IM Pace) + Strength B",
      Fri: "Swim: 2.0 km (Tempo)",
      Sat: "Long Ride: 3.2 hours + Brick Run: 20 min",
      Sun: "Long Run: 1.8 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "04/12/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.0 km (Technique) + Strength A",
      Tue: "Bike: 90 min (3x15min @ IM Pace)",
      Wed: "Swim: 2.2 km (Endurance)",
      Thu: "Run: 10 km (2x15min @ IM Pace) + Strength B",
      Fri: "Swim: 2.0 km (Tempo)",
      Sat: "Long Ride: 3.3 hours + Brick Run: 20 min",
      Sun: "Long Run: 1.9 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "04/19/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.0 km (Technique) + Strength A",
      Tue: "Bike: 90 min (3x15min @ IM Pace)",
      Wed: "Swim: 2.2 km (Endurance)",
      Thu: "Run: 10 km (2x15min @ IM Pace) + Strength B",
      Fri: "Swim: 2.0 km (Tempo)",
      Sat: "Long Ride: 3.5 hours + Brick Run: 20 min",
      Sun: "Long Run: 1.9 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "04/26/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 2.0 hours + Brick Run: 15 min",
      Sun: "Long Run: 1.5 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "05/03/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.2 km (Technique) + Strength A",
      Tue: "Bike: 100 min (3x16min @ IM Pace)",
      Wed: "Swim: 2.4 km (Endurance)",
      Thu: "Run: 11 km (2x16min @ IM Pace) + Strength B",
      Fri: "Swim: 2.2 km (Tempo)",
      Sat: "Long Ride: 4.1 hours + Brick Run: 25 min",
      Sun: "Long Run: 2.1 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "05/10/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.2 km (Technique) + Strength A",
      Tue: "Bike: 100 min (3x16min @ IM Pace)",
      Wed: "Swim: 2.4 km (Endurance)",
      Thu: "Run: 11 km (2x16min @ IM Pace) + Strength B",
      Fri: "Swim: 2.2 km (Tempo)",
      Sat: "Long Ride: 4.2 hours + Brick Run: 25 min",
      Sun: "Long Run: 2.2 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "05/17/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.2 km (Technique) + Strength A",
      Tue: "Bike: 100 min (3x16min @ IM Pace)",
      Wed: "Swim: 2.4 km (Endurance)",
      Thu: "Run: 11 km (2x16min @ IM Pace) + Strength B",
      Fri: "Swim: 2.2 km (Tempo)",
      Sat: "Long Ride: 4.4 hours + Brick Run: 25 min",
      Sun: "Long Run: 2.2 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "05/24/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 2.4 hours + Brick Run: 15 min",
      Sun: "Long Run: 1.6 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "05/31/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.4 km (Technique) + Strength A",
      Tue: "Bike: 110 min (3x17min @ IM Pace)",
      Wed: "Swim: 2.6 km (Endurance)",
      Thu: "Run: 12 km (2x17min @ IM Pace) + Strength B",
      Fri: "Swim: 2.4 km (Tempo)",
      Sat: "Long Ride: 5.0 hours + Brick Run: 30 min",
      Sun: "Long Run: 2.4 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "06/07/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.4 km (Technique) + Strength A",
      Tue: "Bike: 110 min (3x17min @ IM Pace)",
      Wed: "Swim: 2.6 km (Endurance)",
      Thu: "Run: 12 km (2x17min @ IM Pace) + Strength B",
      Fri: "Swim: 2.4 km (Tempo)",
      Sat: "Long Ride: 5.1 hours + Brick Run: 30 min",
      Sun: "Long Run: 2.5 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "06/14/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.4 km (Technique) + Strength A",
      Tue: "Bike: 110 min (3x17min @ IM Pace)",
      Wed: "Swim: 2.6 km (Endurance)",
      Thu: "Run: 12 km (2x17min @ IM Pace) + Strength B",
      Fri: "Swim: 2.4 km (Tempo)",
      Sat: "Long Ride: 5.3 hours + Brick Run: 30 min",
      Sun: "Long Run: 2.5 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "06/21/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 3.3 hours + Brick Run: 15 min",
      Sun: "Long Run: 1.8 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "06/28/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.6 km (Technique) + Strength A",
      Tue: "Bike: 120 min (3x18min @ IM Pace)",
      Wed: "Swim: 2.8 km (Endurance)",
      Thu: "Run: 13 km (2x18min @ IM Pace) + Strength B",
      Fri: "Swim: 2.6 km (Tempo)",
      Sat: "Long Ride: 5.9 hours + Brick Run: 35 min",
      Sun: "Long Run: 2.7 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "07/05/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.6 km (Technique) + Strength A",
      Tue: "Bike: 120 min (3x18min @ IM Pace)",
      Wed: "Swim: 2.8 km (Endurance)",
      Thu: "Run: 13 km (2x18min @ IM Pace) + Strength B",
      Fri: "Swim: 2.6 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 35 min",
      Sun: "Long Run: 2.8 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "07/12/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.6 km (Technique) + Strength A",
      Tue: "Bike: 120 min (3x18min @ IM Pace)",
      Wed: "Swim: 2.8 km (Endurance)",
      Thu: "Run: 13 km (2x18min @ IM Pace) + Strength B",
      Fri: "Swim: 2.6 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 35 min",
      Sun: "Long Run: 2.8 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "07/19/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 4.0 hours + Brick Run: 15 min",
      Sun: "Long Run: 2.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "07/26/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.8 km (Technique) + Strength A",
      Tue: "Bike: 130 min (3x19min @ IM Pace)",
      Wed: "Swim: 3.0 km (Endurance)",
      Thu: "Run: 14 km (2x19min @ IM Pace) + Strength B",
      Fri: "Swim: 2.8 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 40 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "08/02/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.8 km (Technique) + Strength A",
      Tue: "Bike: 130 min (3x19min @ IM Pace)",
      Wed: "Swim: 3.0 km (Endurance)",
      Thu: "Run: 14 km (2x19min @ IM Pace) + Strength B",
      Fri: "Swim: 2.8 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 40 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "08/09/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 2.8 km (Technique) + Strength A",
      Tue: "Bike: 130 min (3x19min @ IM Pace)",
      Wed: "Swim: 3.0 km (Endurance)",
      Thu: "Run: 14 km (2x19min @ IM Pace) + Strength B",
      Fri: "Swim: 2.8 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 40 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "08/16/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 4.0 hours + Brick Run: 15 min",
      Sun: "Long Run: 2.2 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "08/23/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 3.0 km (Technique) + Strength A",
      Tue: "Bike: 140 min (3x20min @ IM Pace)",
      Wed: "Swim: 3.2 km (Endurance)",
      Thu: "Run: 15 km (2x20min @ IM Pace) + Strength B",
      Fri: "Swim: 3.0 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 45 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "08/30/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 3.0 km (Technique) + Strength A",
      Tue: "Bike: 140 min (3x20min @ IM Pace)",
      Wed: "Swim: 3.2 km (Endurance)",
      Thu: "Run: 15 km (2x20min @ IM Pace) + Strength B",
      Fri: "Swim: 3.0 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 45 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "09/06/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "IM Build",
      Mon: "Swim: 3.0 km (Technique) + Strength A",
      Tue: "Bike: 140 min (3x20min @ IM Pace)",
      Wed: "Swim: 3.2 km (Endurance)",
      Thu: "Run: 15 km (2x20min @ IM Pace) + Strength B",
      Fri: "Swim: 3.0 km (Tempo)",
      Sat: "Long Ride: 6.0 hours + Brick Run: 45 min",
      Sun: "Long Run: 3.0 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "09/13/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Deload",
      Mon: "Swim: 2.0 km Easy + Strength A (light)",
      Tue: "Bike: 60 min (Easy)",
      Wed: "Swim: 2.0 km Easy",
      Thu: "Run: 8 km (Easy) + Strength B (light)",
      Fri: "REST",
      Sat: "Long Ride: 4.0 hours + Brick Run: 15 min",
      Sun: "Long Run: 2.2 hours",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "09/20/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Taper",
      Mon: "Swim: 2.0 km (Easy)",
      Tue: "Bike: 45 min (Easy)",
      Wed: "Swim: 1.5 km (Easy)",
      Thu: "Run: 6 km (Easy)",
      Fri: "REST",
      Sat: "Bike: 2.0 hours (Easy) + Brick Run: 10 min",
      Sun: "Run: 1.0 hour (Easy)",
      "Total Run km": "N/A (Triathlon)",
    },
    {
      "Week Start": "09/27/2027",
      Phase: "Phase 3: Ironman Training",
      "Week Type": "Race Week",
      Mon: "Swim: 1.5 km (Easy)",
      Tue: "Bike: 30 min (Spin)",
      Wed: "OFF",
      Thu: "Run: 4 km (Easy)",
      Fri: "REST",
      Sat: "OFF",
      Sun: "RACE: Ironman Barcelona!",
      "Total Run km": "N/A (Triathlon)",
    },

    // --- ULTRA MARATHON PHASE (PHASE 4) ---
    {
      "Week Start": "10/04/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "IM Recovery",
      Mon: "OFF",
      Tue: "Light Walk / Mobility",
      Wed: "Run 4 km Easy",
      Thu: "OFF",
      Fri: "Run 4 km Easy",
      Sat: "Run 6 km Easy",
      Sun: "REST",
      "Total Run km": 14,
    },
    {
      "Week Start": "10/11/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "IM Recovery",
      Mon: "OFF",
      Tue: "Strength Day + Run 5 km Easy",
      Wed: "OFF",
      Thu: "Run 6 km Easy",
      Fri: "OFF",
      Sat: "Run 10 km Easy",
      Sun: "REST",
      "Total Run km": 21,
    },
    {
      "Week Start": "10/18/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 8 km (incl. 4 km @ Tempo)",
      Tue: "Strength Day + Run 5 km Easy",
      Wed: "Run 6 km Easy",
      Thu: "Run 8 km Easy",
      Fri: "OFF",
      Sat: "Long Run 16 km (Road/Flat)",
      Sun: "REST",
      "Total Run km": 43,
    },
    {
      "Week Start": "10/25/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 10 km (incl. 5 km @ Tempo)",
      Tue: "Strength Day + Run 5 km Easy",
      Wed: "Run 8 km Easy",
      Thu: "Run 10 km Easy",
      Fri: "OFF",
      Sat: "Long Run 18 km (Road/Flat)",
      Sun: "REST",
      "Total Run km": 51,
    },
    {
      "Week Start": "11/01/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 10 km (incl. 6 km @ Tempo)",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 8 km Easy",
      Thu: "Run 10 km Easy",
      Fri: "OFF",
      Sat: "Long Run 20 km (Intro to Sand)",
      Sun: "REST",
      "Total Run km": 54,
    },
    {
      "Week Start": "11/08/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Deload",
      Mon: "Run 8 km Easy",
      Tue: "Strength Day + Run 5 km Easy",
      Wed: "Run 6 km Easy",
      Thu: "Run 8 km Easy",
      Fri: "OFF",
      Sat: "Long Run 14 km (Road)",
      Sun: "REST",
      "Total Run km": 41,
    },
    {
      "Week Start": "11/15/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 12 km (incl. 2x4 km @ Tempo)",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 22 km (Sand/Trail)",
      Sun: "REST",
      "Total Run km": 62,
    },
    {
      "Week Start": "11/22/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 12 km (incl. 2x4.5 km @ Tempo)",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 24 km (Sand/Trail)",
      Sun: "REST",
      "Total Run km": 64,
    },
    {
      "Week Start": "11/29/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 12 km (incl. 3x3 km @ Tempo)",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 26 km (Sand/Trail)",
      Sun: "REST",
      "Total Run km": 66,
    },
    {
      "Week Start": "12/06/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Deload",
      Mon: "Run 8 km Easy",
      Tue: "Strength Day + Run 5 km Easy",
      Wed: "Run 8 km Easy",
      Thu: "Run 10 km Easy",
      Fri: "OFF",
      Sat: "Long Run 18 km (Road)",
      Sun: "REST",
      "Total Run km": 49,
    },
    {
      "Week Start": "12/13/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 12 km (incl. 9 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 14 km Easy",
      Fri: "OFF",
      Sat: "Long Run 28 km (Sand/Trail)",
      Sun: "B2B Run: 10 km Easy (Sand)",
      "Total Run km": 82,
    },
    {
      "Week Start": "12/20/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 12 km (incl. 2x5 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 14 km Easy",
      Fri: "OFF",
      Sat: "Long Run 30 km (Sand/Trail)",
      Sun: "B2B Run: 12 km Easy (Sand)",
      "Total Run km": 86,
    },
    {
      "Week Start": "12/27/2027",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 14 km (incl. 10 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 14 km Easy",
      Fri: "OFF",
      Sat: "Long Run 32 km (Sand/Trail)",
      Sun: "B2B Run: 14 km Easy (Sand)",
      "Total Run km": 92,
    },
    {
      "Week Start": "01/03/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Deload",
      Mon: "Run 10 km Easy",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 8 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 22 km (Road)",
      Sun: "B2B Run: 8 km Easy (Road)",
      "Total Run km": 66,
    },
    {
      "Week Start": "01/10/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 14 km (incl. 2x5 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 12 km Easy",
      Thu: "Run 16 km Easy",
      Fri: "OFF",
      Sat: "Long Run 34 km (Sand/Trail)",
      Sun: "B2B Run: 15 km Easy (Sand)",
      "Total Run km": 99,
    },
    {
      "Week Start": "01/17/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 14 km (incl. 10 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 12 km Easy",
      Thu: "Run 16 km Easy",
      Fri: "OFF",
      Sat: "Long Run 36 km (Sand/Trail)",
      Sun: "B2B Run: 16 km Easy (Sand)",
      "Total Run km": 102,
    },
    {
      "Week Start": "01/24/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 14 km (incl. 3x4 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 12 km Easy",
      Thu: "Run 16 km Easy",
      Fri: "OFF",
      Sat: "Long Run 38 km (Sand/Trail)",
      Sun: "B2B Run: 18 km Easy (Sand)",
      "Total Run km": 106,
    },
    {
      "Week Start": "01/31/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Deload",
      Mon: "Run 10 km Easy",
      Tue: "Strength Day + Run 6 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 25 km (Road)",
      Sun: "B2B Run: 10 km Easy (Road)",
      "Total Run km": 73,
    },
    {
      "Week Start": "02/07/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 15 km (incl. 2x6 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 14 km Easy",
      Thu: "Run 18 km Easy",
      Fri: "OFF",
      Sat: "Long Run 40 km (Sand/Trail)",
      Sun: "B2B Run: 18 km Easy (Sand)",
      "Total Run km": 113,
    },
    {
      "Week Start": "02/14/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 15 km (incl. 12 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 14 km Easy",
      Thu: "Run 18 km Easy",
      Fri: "OFF",
      Sat: "Long Run 42 km (Sand/Trail)",
      Sun: "B2B Run: 20 km Easy (Sand)",
      "Total Run km": 117,
    },
    {
      "Week Start": "02/21/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Up",
      Mon: "Run 15 km (incl. 3x4 km @ Tempo)",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 14 km Easy",
      Thu: "Run 18 km Easy",
      Fri: "OFF",
      Sat: "Long Run 45 km (Sand/Trail)",
      Sun: "B2B Run: 20 km Easy (Sand)",
      "Total Run km": 120,
    },
    {
      "Week Start": "02/28/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Deload",
      Mon: "Run 10 km Easy",
      Tue: "Strength Day + Run 8 km Easy",
      Wed: "Run 10 km Easy",
      Thu: "Run 14 km Easy",
      Fri: "OFF",
      Sat: "Long Run 28 km (Road)",
      Sun: "B2B Run: 12 km Easy (Road)",
      "Total Run km": 82,
    },
    {
      "Week Start": "03/06/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Peak",
      Mon: "Run 15 km (incl. 2x6 km @ Tempo)",
      Tue: "Strength Day + Run 10 km Easy",
      Wed: "Run 15 km Easy",
      Thu: "Run 20 km Easy",
      Fri: "OFF",
      Sat: "Long Run 45 km (Sand/Trail)",
      Sun: "B2B Run: 22 km Easy (Sand)",
      "Total Run km": 127,
    },
    {
      "Week Start": "03/13/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Peak",
      Mon: "Run 15 km (incl. 12 km @ Tempo)",
      Tue: "Strength Day + Run 10 km Easy",
      Wed: "Run 15 km Easy",
      Thu: "Run 20 km Easy",
      Fri: "OFF",
      Sat: "Long Run 45 km (Sand/Trail)",
      Sun: "B2B Run: 25 km Easy (Sand)",
      "Total Run km": 130,
    },
    {
      "Week Start": "03/20/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Peak",
      Mon: "Run 12 km Easy",
      Tue: "Light Mobility + Run 10 km Easy",
      Wed: "Run 15 km Easy",
      Thu: "Run 15 km Easy",
      Fri: "OFF",
      Sat: "Long Run 45 km (Sand/Trail)",
      Sun: "B2B Run: 25 km Easy (Sand)",
      "Total Run km": 122,
    },
    {
      "Week Start": "03/27/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Taper 1",
      Mon: "Run 10 km Easy",
      Tue: "Light Mobility + Run 8 km Easy",
      Wed: "Run 12 km Easy",
      Thu: "Run 12 km Easy",
      Fri: "OFF",
      Sat: "Long Run 28 km (Sand/Trail)",
      Sun: "B2B Run: 10 km Easy (Sand)",
      "Total Run km": 80,
    },
    {
      "Week Start": "04/03/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Taper 2",
      Mon: "Run 8 km Easy",
      Tue: "Light Mobility",
      Wed: "Run 10 km Easy",
      Thu: "Run 10 km Easy",
      Fri: "OFF",
      Sat: "Long Run 18 km (Sand/Trail)",
      Sun: "REST",
      "Total Run km": 46,
    },
    {
      "Week Start": "04/10/2028",
      Phase: "Phase 4: Belgian Coast Ultra Training",
      "Week Type": "Race Week",
      Mon: "Run 6 km Easy",
      Tue: "Light Mobility",
      Wed: "Run 5 km Easy + 4x Strides",
      Thu: "OFF",
      Fri: "Run 4 km Shakeout",
      Sat: "RACE: 67km Belgian Coast Ultra!",
      Sun: "REST",
      "Total Run km": 82,
    }
  ]
};